package de.kreuter.hgis.common;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;
import java.util.UUID;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.CsvSource;
import org.junit.jupiter.params.provider.ValueSource;

class SqlIdentifierTest {

	@ParameterizedTest
	@CsvSource({
			"Gebäudehöhe,      gebaeudehoehe",
			"Straße,           strasse",
			"Fläche m²,        flaeche_m",
			"NUTZUNGS-ART,     nutzungs_art",
			"  spaces  here  , spaces_here",
			"café,             cafe",
			"2024_wert,        c_2024_wert",
			"___,              col",
			"'',               col",
	})
	@DisplayName("normalises names to safe lowercase identifiers")
	void normalisesNames(String source, String expected) {
		assertThat(SqlIdentifier.toColumnName(source, Set.of())).isEqualTo(expected);
	}

	@Test
	@DisplayName("keeps clear of the reserved fid and geom columns")
	void avoidsReservedNames() {
		assertThat(SqlIdentifier.toColumnName("geom", Set.of())).isEqualTo("geom_1");
		assertThat(SqlIdentifier.toColumnName("fid", Set.of())).isEqualTo("fid_1");
	}

	@Test
	@DisplayName("resolves collisions with an ascending suffix")
	void resolvesCollisions() {
		Set<String> taken = new LinkedHashSet<>();
		// All four normalise to "name": case folding, a trailing symbol and surrounding
		// whitespace all collapse away. Umlauts do not -- "näme" becomes "naeme".
		for (String source : List.of("Name", "NAME", "name!", "  name  ")) {
			taken.add(SqlIdentifier.toColumnName(source, taken));
		}
		assertThat(taken).containsExactly("name", "name_1", "name_2", "name_3");
	}

	@Test
	@DisplayName("truncates to 63 characters and stays unique when truncated")
	void truncatesButStaysUnique() {
		String longName = "a".repeat(200);
		Set<String> taken = new LinkedHashSet<>();

		String first = SqlIdentifier.toColumnName(longName, taken);
		taken.add(first);
		String second = SqlIdentifier.toColumnName(longName, taken);

		assertThat(first).hasSize(SqlIdentifier.MAX_LENGTH);
		assertThat(second).hasSizeLessThanOrEqualTo(SqlIdentifier.MAX_LENGTH);
		// The suffix must survive truncation, otherwise both names collapse into one.
		assertThat(second).isNotEqualTo(first).endsWith("_1");
	}

	@ParameterizedTest
	@ValueSource(strings = {
			"name\"; DROP TABLE gis_meta.project; --",
			"name'; DELETE FROM layer; --",
			"na me",
			"NAME",
			"1col",
			"col-name",
			"",
	})
	@DisplayName("rejects unsafe column identifiers when quoting")
	void rejectsUnsafeColumns(String unsafe) {
		assertThatThrownBy(() -> SqlIdentifier.quoteColumn(unsafe))
				.isInstanceOf(IllegalArgumentException.class);
	}

	@Test
	@DisplayName("normalised injection attempts are harmless and quotable")
	void normalisedInjectionIsHarmless() {
		String normalised = SqlIdentifier.toColumnName("name\"; DROP TABLE project; --", Set.of());

		assertThat(SqlIdentifier.isValidColumn(normalised)).isTrue();
		assertThat(normalised).doesNotContain("\"", ";", "-", " ");
		assertThat(SqlIdentifier.quoteColumn(normalised)).isEqualTo('"' + normalised + '"');
	}

	@Test
	@DisplayName("derives the table name purely from the layer id")
	void derivesTableName() {
		UUID id = UUID.fromString("019fec35-6373-76e1-b5a4-26943cb0a780");
		String tableName = SqlIdentifier.tableName(id);

		assertThat(tableName).isEqualTo("layer_019fec35637376e1b5a426943cb0a780");
		assertThat(SqlIdentifier.isValidLayerTable(tableName)).isTrue();
		assertThat(SqlIdentifier.quoteLayerTable(tableName))
				.isEqualTo("gis_data.\"" + tableName + '"');
	}

	@ParameterizedTest
	@ValueSource(strings = {
			"layer_1",
			"project",
			"layer_019fec35637376e1b5a426943cb0a78",
			"layer_019FEC35637376E1B5A426943CB0A780",
			"layer_x19fec35637376e1b5a426943cb0a780",
	})
	@DisplayName("rejects table names that were not generated by us")
	void rejectsForeignTableNames(String tableName) {
		assertThat(SqlIdentifier.isValidLayerTable(tableName)).isFalse();
		assertThatThrownBy(() -> SqlIdentifier.quoteLayerTable(tableName))
				.isInstanceOf(IllegalArgumentException.class);
	}
}
